# Generated by Django 5.2.8 on 2025-11-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='When anomaly occurred')),
                ('anomaly_type', models.CharField(choices=[('spike', 'Spike'), ('dropout', 'Dropout'), ('out_of_range', 'Out of Range')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('value', models.FloatField(help_text='Value that triggered anomaly')),
                ('expected_range_min', models.FloatField(blank=True, null=True)),
                ('expected_range_max', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Anomaly',
                'verbose_name_plural': 'Anomalies',
                'db_table': 'anomalies',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_id', '-timestamp'], name='anomalies_sensor__b9720d_idx'), models.Index(fields=['timestamp'], name='anomalies_timesta_68083d_idx'), models.Index(fields=['severity', '-timestamp'], name='anomalies_severit_7df53e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensorAggregated1Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Aggregation window start time (hour precision)')),
                ('avg', models.FloatField(help_text='Average value')),
                ('min', models.FloatField(help_text='Minimum value')),
                ('max', models.FloatField(help_text='Maximum value')),
                ('std', models.FloatField(blank=True, help_text='Standard deviation', null=True)),
                ('count', models.IntegerField(help_text='Number of readings in aggregation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '1-Hour Aggregation',
                'verbose_name_plural': '1-Hour Aggregations',
                'db_table': 'sensor_aggregated_1hour',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_id', '-timestamp'], name='sensor_aggr_sensor__2c8ca8_idx'), models.Index(fields=['timestamp'], name='sensor_aggr_timesta_3135e3_idx')],
                'unique_together': {('sensor_id', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SensorAggregated1Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Aggregation window start time (minute precision)')),
                ('avg', models.FloatField(help_text='Average value')),
                ('min', models.FloatField(help_text='Minimum value')),
                ('max', models.FloatField(help_text='Maximum value')),
                ('std', models.FloatField(blank=True, help_text='Standard deviation', null=True)),
                ('count', models.IntegerField(help_text='Number of readings in aggregation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '1-Minute Aggregation',
                'verbose_name_plural': '1-Minute Aggregations',
                'db_table': 'sensor_aggregated_1min',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_id', '-timestamp'], name='sensor_aggr_sensor__9fa8a4_idx'), models.Index(fields=['timestamp'], name='sensor_aggr_timesta_7bba16_idx')],
                'unique_together': {('sensor_id', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SensorAggregated1Sec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Aggregation window start time (second precision)')),
                ('avg', models.FloatField(help_text='Average value')),
                ('min', models.FloatField(help_text='Minimum value')),
                ('max', models.FloatField(help_text='Maximum value')),
                ('std', models.FloatField(blank=True, help_text='Standard deviation', null=True)),
                ('count', models.IntegerField(help_text='Number of readings in aggregation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '1-Second Aggregation',
                'verbose_name_plural': '1-Second Aggregations',
                'db_table': 'sensor_aggregated_1sec',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_id', '-timestamp'], name='sensor_aggr_sensor__788be1_idx'), models.Index(fields=['timestamp'], name='sensor_aggr_timesta_6e38da_idx')],
                'unique_together': {('sensor_id', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField(db_index=True, help_text='Sensor ID (1-12)')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Reading timestamp with microsecond precision')),
                ('value', models.FloatField(help_text='Sensor reading value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sensor Reading',
                'verbose_name_plural': 'Sensor Readings',
                'db_table': 'sensor_readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor_id', '-timestamp'], name='sensor_read_sensor__ecf3b4_idx'), models.Index(fields=['timestamp'], name='sensor_read_timesta_56e803_idx')],
            },
        ),
    ]
